# Generated by Django 4.1.2 on 2022-10-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('poster_url', models.CharField(max_length=2083)),
                ('grade', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=2083)),
            ],
        ),
    ]
